<?php
namespace app\index\controller;

class Mine extends Common
{
    protected $need_login = true;

    /**
     * 用户模型实例
     * @var \app\common\model\Users
     */
    protected $user_model;
    protected $user_model_info;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //模型信息
        $this->user_model = new \app\common\model\Users();
        $this->user_model_info = $this->user_model->get($this->user_id);

    }

    //我的首页
    public function index()
    {
        return view('index',[
            'user_model_info' => $this->user_model_info
        ]);
    }

    //资料
    public function personal()
    {
        //邀请我的人
        $direct_req_user_info = $this->user_model_info ? $this->user_model_info->linkDirectFuid:null;
        return view('personal',[
            'user_model_info' => $this->user_model_info,
            'user_model'      => $this->user_model,
            'direct_req_user_info'      => $direct_req_user_info,
        ]);
    }

    //调整用户资料
    public function modInfo()
    {
        //限制可修改的字段
        $type = $this->request->param('type','');
        $limit_fields = ['face'=>'','name'=>'','city'=>0];
        $php_input = $this->request->param();
        $php_input = array_filter(array_intersect_key($php_input,$limit_fields));
        if($type=='face'){
            //上传用户头像
            $upload =  new Upload();
            $result = $upload->upload($type);
            $result['code'] && $php_input['face'] = $result['path'];
        }

        $php_input['id']= $this->user_id;
        $handle_info =  $this->user_model->actionAdd($php_input);
        isset($result['path']) && $handle_info['path']=$result['path'];
        return $handle_info;
    }

    //我的建议
    public function suggest()
    {
        if($this->request->isAjax()){
            $model = new \app\common\model\Suggest();
            $php_input = $this->request->param();
            $php_input['uid']= $this->user_id;
            $validate = new \app\common\validate\Suggest();
            $result=$model->actionAdd($php_input,$validate);
            return ['code'=>$result['code'],'msg'=>$result['code']?'感谢您的反馈，我们会尽快处理':$result['msg']];
        }
        return view('suggest',[

        ]);
    }

    //联系客服
    public function contact()
    {
        return view('contact');
    }

    //关于
    public function about()
    {
        return view('about',[

        ]);
    }
}